# Generated by Django 5.0.6 on 2024-05-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabin_crew_information', '0001_initial'),
        ('flight_crew_information', '0001_initial'),
        ('passenger_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_cabin_crew_chef', models.ManyToManyField(blank=True, related_name='flight_cabin_crew_chef', to='cabin_crew_information.cabincrew')),
                ('flight_cabin_crew_junior', models.ManyToManyField(related_name='flight_cabin_crew_junior', to='cabin_crew_information.cabincrew')),
                ('flight_cabin_crew_senior', models.ManyToManyField(related_name='flight_cabin_crew_senior', to='cabin_crew_information.cabincrew')),
                ('flight_crew_junior', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flight_crew_junior', to='flight_crew_information.flightcrew')),
                ('flight_crew_senior', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flight_crew_senior', to='flight_crew_information.flightcrew')),
                ('flight_crew_trainee', models.ManyToManyField(blank=True, related_name='flight_crew_trainee', to='flight_crew_information.flightcrew')),
                ('flight_passengers', models.ManyToManyField(blank=True, related_name='flight_passengers', to='passenger_information.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=6)),
                ('flight_date', models.DateTimeField()),
                ('flight_duration', models.DurationField()),
                ('flight_distance', models.IntegerField()),
                ('flight_src_country', models.CharField(max_length=255)),
                ('flight_src_city', models.CharField(max_length=255)),
                ('flight_src_airport_name', models.CharField(max_length=255)),
                ('flight_src_airport_code', models.CharField(max_length=3)),
                ('flight_dest_country', models.CharField(max_length=255)),
                ('flight_dest_city', models.CharField(max_length=255)),
                ('flight_dest_airport_name', models.CharField(max_length=255)),
                ('flight_dest_airport_code', models.CharField(max_length=3)),
                ('flight_menu', models.TextField()),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flight_crew_information.vehicletype')),
                ('flight_roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_information.roster')),
            ],
        ),
        migrations.CreateModel(
            name='SharedFlightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_flight_number', models.CharField(max_length=255)),
                ('shared_flight_company', models.CharField(max_length=255)),
                ('connecting_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_information.flight')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='shared_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_information.sharedflightinfo'),
        ),
    ]
