# Generated by Django 5.0.6 on 2024-05-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255)),
                ('vehicle_capacity', models.IntegerField()),
                ('vehicle_seating_plan', models.IntegerField()),
                ('vehicle_menu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=255)),
                ('languages', models.JSONField()),
                ('range', models.IntegerField()),
                ('seniority', models.CharField(max_length=255)),
                ('flight_number', models.JSONField(default=list)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flight_crew_information.vehicletype')),
            ],
        ),
    ]
