# Generated by Django 5.0.6 on 2024-05-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight_crew_information', '0001_initial'),
        ('flight_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcrew',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flight_information.vehicletype'),
        ),
    ]
