# Generated by Django 5.0.6 on 2024-05-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabinCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=255)),
                ('languages', models.JSONField()),
                ('attendant_type', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle', models.JSONField()),
                ('flight_number', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.TextField()),
                ('chef_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabin_crew_information.cabincrew')),
            ],
        ),
    ]
