# Generated by Django 5.0.6 on 2024-05-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabin_crew_information', '0001_initial'),
        ('flight_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabincrew',
            name='vehicle',
            field=models.ManyToManyField(to='flight_information.vehicletype'),
        ),
        migrations.AddField(
            model_name='cabincrew',
            name='dishes',
            field=models.ManyToManyField(to='cabin_crew_information.dish'),
        ),
    ]
